### ISSUE TITLE
Unrecoverable Console Error 

### ISSUE THREAD

**Issue by Tanjitsu** [crosire/scripthookvdotnet#641] opened 2017-07-12 23:03 UTC
Just one for a rainy day when your polishing the console.

[23:51:41] [ERROR] Failed to instantiate script 'FunBox.Stuff' because constructor threw an exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at GTA.Native.ObjectFromNative(Type type, UInt64* value)
   at GTA.Native.Function.Call[T](UInt64 hash, InputArgument[] arguments)
   at FunBox.Stuff.BuildWeaponsGroups()
   at FunBox.Stuff.BuildHashes()
   at FunBox.Stuff..ctor()
[23:51:41] [ERROR] Caught fatal unhandled exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at GTA.Native.ObjectFromNative(Type type, UInt64* value)
   at GTA.Native.Function.Call[T](UInt64 hash, InputArgument[] arguments)
   at GTA.ConsoleScript.OnTick(Object sender, EventArgs e)
   at GTA.Script.raise_Tick(Object value0, EventArgs value1)
   at GTA.Script.MainLoop()
[23:51:42] [INFO] The exception was thrown while executing the script 'GTA.ConsoleScript'.
[23:51:47] [ERROR] Script 'GTA.ConsoleScript' is not responding! Aborting ...

The Native called was..
WeaponGroup group = Function.Call< WeaponGroup >(Hash.GET_WEAPONTYPE_GROUP, hash);

The call has worked fine for a long time so i would assume it was just an interface bug between script reloads but it took down ScripthookDotNet.

**Comment by zorg93** [comment] 2017-07-13 13:37
what does this have to do with the console, seems like the issue is in your BuildWeaponGroups function, care to post that

**Comment by Tanjitsu** [comment] 2017-07-13 20:30
Sorry,  yeah normally when something die's.
The script is aborted.
In the above.. the console died trying to handle the script error.

[23:51:42] [INFO] The exception was thrown while executing the script 'GTA.ConsoleScript'.
[23:51:47] [ERROR] Script 'GTA.ConsoleScript' is not responding! Aborting ...

This caused all scripts to stop working, So one script took down all.

**Comment by Tanjitsu** [comment] 2017-08-11 00:29
System.ArgumentOutOfRangeException: Index and count must refer to a location within the string.
Parameter name: count
   at System.String.Remove(Int32 startIndex, Int32 count)
   at GTA.ConsoleScript.RemoveCharRight()
   at GTA.ConsoleScript.OnKeyDown(Object sender, KeyEventArgs e)
   at GTA.Script.raise_KeyDown(Object value0, KeyEventArgs value1)
   at GTA.Script.MainLoop()
[01:01:49] [INFO] The exception was thrown while executing the script 'GTA.ConsoleScript'.
[01:01:51] [ERROR] Caught unhandled exception:
System.ArgumentOutOfRangeException: Index and count must refer to a location within the string.
Parameter name: count
   at System.String.Remove(Int32 startIndex, Int32 count)
   at GTA.ConsoleScript.RemoveCharRight()
   at GTA.ConsoleScript.OnKeyDown(Object sender, KeyEventArgs e)
   at GTA.Script.raise_KeyDown(Object value0, KeyEventArgs value1)
   at GTA.Script.MainLoop()
[01:01:51] [INFO] The exception was thrown while executing the script 'GTA.ConsoleScript'.

**Comment by kagikn** [comment] 2017-10-07 13:02
e89fded didn't close this issue (because of wrong format to close, I think), closed this issue.

**Closed by kagikn** 2017-10-07 13:02 UTC
