### ISSUE TITLE
Trying to spawn visual effects

### ISSUE THREAD

**Issue by AAYapps** [crosire/scripthookvdotnet#312] opened 2015-09-12 19:20 UTC
Is there any way to spawn and control visual effects in GTA 5. I am looking all over the place to see if there is a way but I am not sure where to look. I tried using the example code from here

                        var model = new Model(text);
                        model.Request(250);

                        // Check the model is valid
                        if (model.IsInCdImage && model.IsValid)
                        {
                            // Ensure the model is loaded before we try to create it in the world
                            while (!model.IsLoaded) Script.Wait(50);

                            // Create the prop in the world
                            World.CreateProp(model, Game.Player.Character.GetOffsetInWorldCoords(new                    Vector3(0, 5, 0)), true, true);
                        }
                        
                        // Mark the model as no longer needed to remove it from memory.
                        model.MarkAsNoLongerNeeded();

but most of the Items I try to spawn do not appear. I am looking for electric sparks but nothing I put in from objects do not appear. I don't even have control of moving the spawned object. 

Any help?

**Comment by crosire** [comment] 2015-12-21 13:55
Duplicate of #332.

**Closed by crosire** 2015-12-21 13:55 UTC
