### ISSUE TITLE
SHVDN.asi file is crashing game.

### ISSUE THREAD

**Issue by CriminalJustice** [crosire/scripthookvdotnet#1127] opened 2022-12-30 22:05 UTC
I'm still having the same issue with SHVDN that I had before with the most previous version. When I take out the ScriptHookVDotNet.asi file my game runs great, but the second I put that file back in, the game starts crashing. I've tested this many times. This is with the latest version of SHVDN that was just updated yesterday. The other SHVDN files work. The one that doesn't work is the ScriptHookVDotNet.asi file. This new version of GTAV 2802 has really done a number on allot of peoples games.

**Comment by nomakewan** [comment] 2022-12-31 06:59
I cannot replicate this crash. I'm on GTAV v2802, SHVDN 3.6.0, and the only mods I have are BTTFV and its dependencies (FusionLibrary, LemonUI 1.9.1, HeapAdjuster), Menyoo, Stop Reversing While Braking, and DefaultRadioOFF. Everything works perfectly fine. In fact it would load into story mode without crashing with 3.5.1 too.

Are you by chance attempting to use Rage Plugin Hook instead? Or maybe you have some ancient-as-sin .NET mod installed that is the actual culprit of your crashes, which is why disabling SHVDN (which is what you're doing by removing its ASI) "solves" the crash?

**Comment by CriminalJustice** [comment] 2022-12-31 18:09
> I cannot replicate this crash. I'm on GTAV v2802, SHVDN 3.6.0, and the only mods I have are BTTFV and its dependencies (FusionLibrary, LemonUI 1.9.1, HeapAdjuster), Menyoo, Stop Reversing While Braking, and DefaultRadioOFF. Everything works perfectly fine. In fact it would load into story mode without crashing with 3.5.1 too.
> 
> Are you by chance attempting to use Rage Plugin Hook instead? Or maybe you have some ancient-as-sin .NET mod installed that is the actual culprit of your crashes, which is why disabling SHVDN (which is what you're doing by removing its ASI) "solves" the crash?

I am using Rage Plugin Hook. However, I've used Rage Plugin Hook along with ScriptHookVDotNet "together" for a long time and I've never had this issue before. As far as having some "ancient as-in-sin.NET mod installed, not likely. Theres allot of other folks from my community that are having the same exact issue. My current mods I have installed was done on a fresh install of GTAV. Which means I uninstalled and reinstalled GTAV. So all of my files and mods are up to date. The only mod/mods that might be a bit out of date would be a couple of OpenIV modifications but again, they all worked with SHVDN before. So, all my mods are useable except for the scripts in my scripts folder. I'm just here seeking a solution. I can run without scripts but it would be better not to. I'm mainly here looking for a solution for my community. Thank you in advance for any help and thank you for the response.

**Comment by nomakewan** [comment] 2022-12-31 18:16
Okay, so you're using Rage Plugin Hook. Please see the following issues:

#759
#1122 
#1092 
#1057 
#1120 
#1084 

As you can see, the issue is with Rage Plugin Hook. The onus will be on them to update to support the latest SHVDN.

**Comment by CriminalJustice** [comment] 2022-12-31 23:51
> Okay, so you're using Rage Plugin Hook. Please see the following issues:
> 
> #759 #1122 #1092 #1057 #1120 #1084
> 
> As you can see, the issue is with Rage Plugin Hook. The onus will be on them to update to support the latest SHVDN.

Thanks for the help.

**Comment by CriminalJustice** [comment] 2023-01-06 19:28
> > Okay, so you're using Rage Plugin Hook. Please see the following issues:
> > #759 #1122 #1092 #1057 #1120 #1084
> > As you can see, the issue is with Rage Plugin Hook. The onus will be on them to update to support the latest SHVDN.
> 
> Thanks for the help.

Is there a different version that I can use for now that will support the scripts folder and run with the latest version of Rage Plugin Hook?

**Comment by nomakewan** [comment] 2023-01-06 19:47
Due to the changes in v2802 of GTAV, the technical answer is no. Using earlier versions of SHVDN, even if they were to not instantly lead to a crash, could lead to crashes and unintended behavior should certain functions be called. For an example, see #1123 

Because of this, again, the developers of Rage Plugin Hook would need to work to properly support SHVDN 3.6.0.

**Comment by CriminalJustice** [comment] 2023-01-06 19:49
> Due to the changes in v2802 of GTAV, the technical answer is no. Using earlier versions of SHVDN, even if they were to not instantly lead to a crash, could lead to crashes and unintended behavior should certain functions be called. For an example, see #1123
> 
> Because of this, again, the developers of Rage Plugin Hook would need to work to properly support SHVDN 3.6.0.

Alright. thanks again for all the help man. I really appreciate it.

**Comment by Sardelka9515** [comment] 2023-01-21 05:27
Please kindly attach the crash information, which can be normally found in `Event viewer -> Windows logs -> Application`, open the ones with Error label and comes from GTAV.exe, then paste the content here. So we can see what the problem really is.

**Comment by LoganIsLogan14** [comment] 2023-02-07 03:25
I really wish this issue would be taken seriously. I've listened to both developers' side of the story, and I hear the same thing every time, Oh that's a SHVDN problem, they need to fix it, or, Oh that's a RPH problem, they need to fix it. Why can't both parties come together and fix this. This bug has really ruined my modding experience with GTAV. Specifically playing LSPDFR with scripts installed. It seems like they were onto something in this issue. [#976 ](https://github.com/crosire/scripthookvdotnet/issues/976)
If it helps any, this issue started when I upgraded my GPU from a 2060 Super, to a 2080ti.

**Comment by nomakewan** [comment] 2023-02-07 04:31
Might have something to do with RPH being closed-source, while SHVDN is open-source. Just guessing.

Maybe provide crash logs as Sardelka9515 commented two weeks ago?

**Comment by LoganIsLogan14** [comment] 2023-02-11 00:32
My crash report is in my original post, and yeah that could have something to do with it, but if it really is something on SHVDN's side, [#976](https://github.com/crosire/scripthookvdotnet/issues/976) was on to something.

**Comment by crosire** [comment] 2023-02-18 11:54
Closing as duplicate of #759.

**Closed by crosire** 2023-02-18 11:54 UTC
Labels: duplicate

**Comment by LegacyEffect** [comment] 2023-04-13 07:09
Close these threads all you want, but just know this is still an ongoing issue and this is getting old super fast.

**Comment by nomakewan** [comment] 2023-04-13 07:52
> Close these threads all you want, but just know this is still an ongoing issue and this is getting old super fast.

You literally have no idea what you are talking about. Maybe you should build SHVDN from source (or download one of the artifacts from the AppVeyor build bot) and test it before spamming nonsense. Not doing so makes you look very foolish.
