### ISSUE TITLE
Vehicle.PlaceOnNextStreet Heap Corruption

### ISSUE THREAD

**Issue by applebus** [crosire/scripthookvdotnet#91] opened 2015-05-17 22:53 UTC
World.CreateVehicle(VehicleHash.PoliceT,Game.Player.Character.Position.Around(100));
        _veh.PlaceOnNextStreet();

Causes a heap corruption error, wrote to memory after heap buffer.

**Comment by IncoCode** [comment] 2015-05-18 04:24
```c#
Vehicle veh = World.CreateVehicle(VehicleHash.PoliceT,Game.Player.Character.Position.Around(100));
veh.PlaceOnNextStreet();
```
?

**Comment by Nacorpio** [comment] 2015-05-18 12:18
LOL.

**Comment by JohnnyCrazy** [comment] 2015-05-21 16:20
Are you sure you used it correctly?
Can you try IncoCode's snippet and report back?

**Comment by applebus** [comment] 2015-05-23 20:16
Tested with just the above snippet called from a keydown. You can ignore out of it and be fine, so no others see this as well?
![image](https://cloud.githubusercontent.com/assets/1331490/7785637/b3dcd712-0166-11e5-8836-9c2bb24721e2.png)

**Comment by JohnnyCrazy** [comment] 2015-05-23 22:34
Does it always occure after the Create-Method? Or does it also occur on other calls/maybe even random?

**Comment by applebus** [comment] 2015-05-23 22:47
Yes, having only the above snippet I can replicate at will with any vehicle.
Removing PlaceOnNextStreet() stops the error. I can do anything else in the vehicle class no problem.

**Comment by crosire** [comment] 2015-05-24 11:08
What we are asking for here is some small script to reproduce this. =)

**Comment by applebus** [comment] 2015-05-29 17:43
Vehicle veh = World.CreateVehicle(VehicleHash.PoliceT,Game.Player.Character.Position.Around(100));
    veh.PlaceOnNextStreet();

**Comment by nevadascout** [comment] 2015-05-31 21:26
Using that exact code I am unable to reproduce this.

I've tested with both `onKeyUp` and `onKeyDown` with no problems at all.

**Comment by JohnnyCrazy** [comment] 2015-06-04 18:48
@applebus 
I think there is something wrong either with your game files or with your ram (Maybe run memtest for some time checking everything is alright), since noone except you reported the same error. I will close this, but feel free to add comments if you experience the same!

**Closed by JohnnyCrazy** 2015-06-04 18:48 UTC
Labels: needs feedback
