### ISSUE TITLE
Is there a way to create particle effects

### ISSUE THREAD

**Issue by AAYapps** [crosire/scripthookvdotnet#328] opened 2015-09-25 14:52 UTC
I have tryed to get particle effects working. 

I found these hashs but I can't get them to work

START_PARTICLE_FX_NON_LOOPED_ON_ENTITY or START_PARTICLE_FX_LOOPED_ON_ENTITY
REQUEST_NAMED_PTFX_ASSET 
_SET_PTFX_ASSET_NEXT_CALL

I am using the                       

Function.Call(.....)

with all of these

                if (e.KeyCode == Keys.U)
                {
                    Function.Call<bool>(Hash.START_PARTICLE_FX_NON_LOOPED_ON_ENTITY, "scr_fbi4", (Entity)Game.Player.Character, 2, 2, 2, 2, 2, 2, 10, false, false, false);
                    Function.Call(Hash.REQUEST_NAMED_PTFX_ASSET, "scr_fbi4");
                    Function.Call(Hash._SET_PTFX_ASSET_NEXT_CALL, "scr_fbi4");
                }

any help please

**Comment by crosire** [comment] 2015-12-21 13:51
Duplicate of #332.

**Closed by crosire** 2015-12-21 13:51 UTC
