### ISSUE TITLE
Game crash when marking many peds as no longer needed

### ISSUE THREAD

**Issue by sayagohren** [crosire/scripthookvdotnet#938] opened 2020-06-28 13:07 UTC
**Version**
ScriptHookVDotNet v3.0.3

**Description**
 Hello, I have encountered the problem why trying to use the function **MarkAsNoLongerNeeded()** in my police mod which spawns extra cars with law forces (not editing dispatch.meta) .

When the player gets wanted level zero I mark all spawned cars and peds in them as no needed, but if there are many of them (about to 20-25 cars full of peds and about 5 helicopters) the game just crashes.

If not many cars are spawned everything works fine.

Application error in windows event viewer:
Application: GTA5.exe
Platform Version: v4.0.30319
Description. The process was completed due to an unhandled exception.
Exception Details: System.AccessViolationException
   at SHVDN.NativeFunc.NativeCall ()
   at SHVDN.NativeFunc.NativeTask.Run ()
   at SHVDN.ScriptDomain.DoTick ()
   at SHVDN.ScriptDomain.DoTick ()
   in <Module>.? A0xc1aa4bd5.ScriptHookVDotnet_ManagedTick ()

The strange thing is that if I just spawn a big group of peds without cars ( up to 200 cops) and then mark them as no longer needed everything is fine.

Also want to notice if I use another function instead of this (for example entity.delete) it also works correctly.
Maybe the crash happens because of many peds sitting in cars, but it is also strange.

Hope this question will be reviewed, I can not finish my first mod because of these crashes. I am ready to provide any extra information needed.

**Comment by PietroKaro** [comment] 2020-07-02 12:38
I pratically made your same mod and maybe i have the same problem. In my mod i created a method calls "Reset()" that mark vehicle and ped as no longer needed when player is dead, wanted level is 0 or there are too much vehicles and peds. I saw that sometimes, when cops kill me, the game crash during the "wasted screen" (the moment when "Reset()" is called) and in windows event viewer, i read the problem's description:

System.AccessViolationException
   in SHVDN.NativeFunc.NativeCall()
   in SHVDN.NativeFunc.NativeTask.Run()
   in SHVDN.ScriptDomain.DoTick()
   in SHVDN.ScriptDomain.DoTick()
   in <Module>.?A0xc1aa4bd5.ScriptHookVDotnet_ManagedTick()

**Comment by sayagohren** [comment] 2020-07-02 18:27
It is interesting, did you try to replace MarkAsNoLongerNeeded()  with Delete()? If it is the same problem you will not have game crashes, but it is not the solution. I will try at weekend to spawn about 20-30 cars full of peds and then marking them as no needed and write the result here. Making such kind of trick simply with peds (200 peds spawned) do not trigger crash. Strange situation.

**Comment by PietroKaro** [comment] 2020-07-02 19:17
I will try too with Delete() method. 👍 
In native db there are more functions permit you to mark a specific entity as no longer needed. I paste the framework documentation about System.AccessViolationException:
https://docs.microsoft.com/it-it/dotnet/api/system.accessviolationexception?view=netcore-3.1

![nativedb](https://user-images.githubusercontent.com/59518978/86400681-5c2a6a80-bca9-11ea-96ba-27b031e36d76.png)

**Comment by sayagohren** [comment] 2020-07-02 19:38
I saw that functions but I did not succeed in calling them directly(, I always receive an "Access Violation error", although I am a neewer in scripting  it seems to me that crashes happen due to invalid pointers, because as I understand in dot net source code the handle for entity is identificated and only then the function is called.

**Comment by sayagohren** [comment] 2020-07-05 08:42
As promised tested an issue with spawning cars with peds. As I thought game crashes when you spawn peds in cars (after using on peds **MarkAsNoLongerNeeded()** ) but does not crash when you spawn just peds on ground (even many). 

After testing I can say exact tning: game starts to crash when I spawn more than 6 vehicles (in my test it was Riot2) and then mark peds in it as no longer needed.

If I do same things with six or less vehicles everything is okay. If I use **entity.Delete()** method instead of **MarkAsNoLongerNeeded()** everything is okay even with 15 cars.  I can not understand the logic and the reason of this problem...

**Comment by PietroKaro** [comment] 2020-07-05 16:57
Same thing to me :/ (6-8 police riot and for each riot, there was 8 ped). Me too Entity.Delete() works fine.

**Comment by PietroKaro** [comment] 2020-07-05 17:04
I think the problem is in ScriptHookV and not in SHVDN because the exception is in NativeCall method and the function is called externally:

https://github.com/crosire/scripthookvdotnet/blob/c82bbf29d40609ebc9fe49ed311ca74f96ee2607/source/core/NativeFunc.cs#L37

**Comment by sayagohren** [comment] 2020-07-05 20:43
If so it can be a problem because script hook V is not hosted on github, only on authors site, where I can not find place to give a feedback.

 Maybe the problem can be linked with gameconfig limits, perhaps some kind of scenario limits? I suppose so because after marking as no needed peds execute simple scenario: fly/go/drive away. 

Anyway I hope the author of scripthookdotnet will give a comment.

**Comment by PietroKaro** [comment] 2020-07-06 13:21
I saw in GTA Mods forums that some people blame the gameconfig file and they tell that you can change the max value of spawned peds/vehicles. I'm not sure if this is the solution but if so, it would be very annoying because i would like to make mods without modify any game file.

**Comment by PietroKaro** [comment] 2020-07-20 12:01
UPDATE:

It seems that the game crashes when you mark as no longer needed more than 35-39 cops in vehicles (i tried to spawn 5 police riots and for each riot i created 8 peds for a total of 40 peds in vehicles). I did the same thing with ped model "Agent14" but the game crashed after i called MarkAsNoLongerNeeded() for about 80 peds in riots.

**Comment by sayagohren** [comment] 2020-07-20 20:28
Thanks for feedback. If I understand correctly the amount of peds in vehicles that causes crash depends on ped models used? You make peds like cops? (SET_PED_AS_COP)  I will try to test this issue with ped models on weekend.

**Comment by PietroKaro** [comment] 2020-07-21 16:27
I saw your post on GTAForum. I did other tests in my game about this problem and i will post the results on forum. Here we should wait an answer from crosire or contributors (i'm sure they can tell us more about the problem because i know enough C# but i'm not very expert about low-level memory management ;) ).

**Comment by Dilapidated** [comment] 2020-07-23 02:01
I had a similar issue in the past and it turned out I was able to resolve it by editing/adding some specific lines to gameconfig.xml. Try this and tell me if it resolves your issue:

```
					<Item>
						<!-- R* cap = 31 : Increasing this value in addition to CEvent can resolve GTA.Native.?A0x55605b1d.NativeTask.Run() crashes in wineventlog -->
						<PoolName>ctasksequencelist</PoolName>
						<PoolSize value="200"/>
					</Item>

					<Item>
					<!-- Increasing this value in addition to ctasksequencelist can resolve GTA.Native.?A0x55605b1d.NativeTask.Run() crashes in wineventlog -->
						<PoolName>CEvent</PoolName>
						<PoolSize value="4000"/>
					</Item>
```

**Comment by sayagohren** [comment] 2020-07-23 20:22
> 
> 
> I had a similar issue in the past and it turned out I was able to resolve it by editing/adding some specific lines to gameconfig.xml. Try this and tell me if it resolves your issue:
> ctasksequencelist will need to be added.
> CEvent will need to be edited.
> 
> ```
> 					<Item>
> 						
> 						<PoolName>ctasksequencelist</PoolName>
> 						<PoolSize value="200"/>
> 					</Item>
> 
> 					<Item>
> 					
> 						<PoolName>CEvent</PoolName>
> 						<PoolSize value="4000"/>
> 					</Item>
> ```
> 
> Alternatively you can try using this gameconfig I recently created for RDE 4.0: https://cdn.discordapp.com/attachments/344962468029792256/723610657022410802/gameconfig.xml

It is great, everything works fine!! Thank you alot, so simple and effective. As I thought it was linked with shitty R* limits. The issue can be closed. One off-topic question, can you say which parameters in config can permit spawning of many enemies - peds and cars at one time without game crash (for example about 50 cars full of police peds), or it is impossible. Thanks.

**Comment by Dilapidated** [comment] 2020-07-24 23:18
Awesome! Happy I could help you get this resolved. As for your off-topic question: Peds are hardcode limited to a max of 256, this is regardless of what you do to gameconfig as it's an exe based limitation. Similarly vehicles are hardcode limited to a max of 300 and again is exe based so changing the gameconfig will not resolve this. Feel free to close this topic if no further questions.

**Closed** 2020-07-25 13:16 UTC
Labels: bug
