### ISSUE TITLE
It does not support gta5 1.39

### ISSUE THREAD

**Issue by pecopeco** [crosire/scripthookvdotnet#607] opened 2017-04-14 02:59 UTC
update it please

**Comment by kagikn** [comment] 2017-04-14 03:03
The 1.39 update didn't even change native hashes, so we don't need to update SHVDN to fix some problems caused by the update. It still works for me without any patches.

**Comment by crosire** [comment] 2017-04-14 11:36
Fixed via 104a10956407ce93e711d2549236600d87254971.

**Closed by crosire** 2017-04-14 11:36 UTC
