### ISSUE TITLE
GTA V CRASH: KERNELBASE.DLL ERROR

### ISSUE THREAD

**Issue by Akertywe** [crosire/scripthookvdotnet#697] opened 2017-09-29 04:37 UTC
Hi i just got a crash when playing GTA V with scripthookdotnet. Here's how it's look in eventviewer:
Faulting application name: GTA5.exe, version: 1.0.1180.2, time stamp: 0x599d9281
Faulting module name: KERNELBASE.dll, version: 6.1.7601.23889, time stamp: 0x598d50ba
Exception code: 0xe0434352
Fault offset: 0x000000000001a06d
Faulting process id: 0x188c
Faulting application start time: 0x01d338da57328130
Faulting application path: E:\Program Files (x86)\Steam Games\steamapps\common\Grand Theft Auto V\GTA5.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: eadf7220-a4ce-11e7-ac68-00ac70c9ea78

AND THIS ONE

Application: GTA5.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at nativeCall()
   at GTA.Native.?A0x55605b1d.NativeTask.Run()
   at GTA.ScriptDomain.DoTick()
   at GTA.ScriptDomain.DoTick()
   at ScriptHookVDotNet.Tick()

Exception Info: System.Reflection.TargetInvocationException
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at <Module>.ManagedTick()

Please help...

**Comment by kagikn** [comment] 2017-09-29 10:32
Run command prompt as administrator and try `regsvr32 KERNELBASE.dll` or `sfc /scannow` in it. This might solve the problem.

**Comment by crosire** [comment] 2017-09-29 16:31
Nah, it just means some script attempted to call a native with an invalid pointer.

**Comment by Akertywe** [comment] 2017-09-29 17:42
@crosire So you mean one of my .net scripts caused this crash?

**Comment by crosire** [comment] 2017-09-29 17:54
Yes

**Comment by kagikn** [comment] 2017-09-30 06:11
I thought wrong, but I hope there are ways to check if the native `NativeTask` is calling exists.

@Akertywe Find out what script cause this expection and contact the author.

**Comment by Akertywe** [comment] 2017-09-30 06:20
@Kagikn It's RDE mod. The author is Dilapidated. I hope he can join this conversation. I've contacted him.

**Comment by Dilapidated** [comment] 2017-09-30 08:57
@kagikn @crosire

We're currently using a native function wrapper to locate the problem function. I was wondering if SHVDN could support advanced exception handling for the event viewer. 

For example would it be possible for SHVDN to provide more details aside from ```at GTA.Native.?A0x55605b1d.NativeTask.Run()```

**Comment by Dilapidated** [comment] 2017-10-02 01:37
So I was able to track down the problem, it actually wasn't an issue with a native call on my end but with IsPersistent in SHVDN. Oddly enough this works 99% of the time but sometimes causes a crash. 

Looking over the code these are my findings...
'IsPersistent = true' equates to
```Native.Function(Hash.SET_ENTITY_AS_MISSION_ENTITY, entity, 1, 1);```
This doesn't appear to cause crashes at all and marks them as persistent correctly

'IsPersistent = false' equates to
```Native.Function(Hash.SET_ENTITY_AS_MISSION_ENTITY, entity, 1, 0);```
This does successfully make the entity no longer persistent but it sometimes will cause the game to crash and when it does the eventlog viewer always gives this error:
```Application: GTA5.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
at nativeCall()
at GTA.Native.?A0x55605b1d.NativeTask.Run()
at GTA.ScriptDomain.DoTick()
at GTA.ScriptDomain.DoTick()
at ScriptHookVDotNet.Tick()```

BUT if I use following native task. 
```Native.Function(Hash.SET_ENTITY_AS_MISSION_ENTITY, entity, 0, 0);```
It makes the entity no longer persistent and does not cause a crash.

Perhaps we should change the 'IsPersistent' SHVDN function so that if its set to false then both bools should be set to false as well. Anyways this was a strange bug that was hard to replicate so I figured I'd share.

**Comment by Tanjitsu** [comment] 2017-10-03 17:26
How many persistent entities did you have ?

GTAV will crash with "Pool Error" if you try to have above a certain no. of persistent entities.

**Comment by DurtyFree** [comment] 2017-10-05 17:06
We over at the GT-MP (Grand Theft Multiplayer) mod also encountered this issue already, we were not able to fix it and it also doesn't seem to be connected to the 'IsPersistent' thing pointed out here.

I think more details or logging possibilities would really help at this point.

**Comment by Dragoon1010** [comment] 2017-10-06 18:47
Me and other people have same problem on GT:MP.

**Comment by crosire** [comment] 2017-10-06 21:03
`IsPersistent = false` actually equates to `Native.Function(Hash.SET_ENTITY_AS_NO_LONGER_NEEDED, &entity.Handle)` which should work. `SET_ENTITY_AS_NO_LONGER_NEEDED` supposedly requires a pointer to the handle, not the handle itself.

**Comment by Dilapidated** [comment] 2017-10-08 04:04
@crosire Interesting. I wonder why `IsPersistent = false` would then cause that crash.

So for testing purposes I tried both the following:
`IsPersistent = false`
AND
`unsafe
        {
            int handle = p.Handle;
            Native.Call(Hash.SET_ENTITY_AS_NO_LONGER_NEEDED, handle);
        }`
Both of these I can confirm crashes my game over a period of time and only when I call this on a ped entity (vehicles don't seem to be affected)

In both instances my crash shows the same event log:
`Application: GTA5.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.AccessViolationException at nativeCall() at GTA.Native.?A0x55605b1d.NativeTask.Run() at GTA.ScriptDomain.DoTick() at GTA.ScriptDomain.DoTick() at ScriptHookVDotNet.Tick()`

Thoughts on how this could be? Could something be wrong with getting a handle for a ped or maybe the handle changing right as using this native?
@Tanjitsu During my testing the amount of persistent entities during my crashes varied. Sometimes I had only 3-5 other times I had 10-20 but never any more than that.

**Comment by Dilapidated** [comment] 2017-10-11 04:41
For reference this is the code I'm using:
`C#
public static Ped CreatePedOnSeat(Vehicle v, int seatNumber, Model model)
    {
        //try
        //{
        //var pedModel = new Model(model); //define model

        if (!model.Request(2000)) //request model
        {
            Log.Write(ScriptName, $"Unable to request the model {model}, does it exist?");
            return null;
        }

        var p = v.CreatePedOnSeat((VehicleSeat) seatNumber, model); //creating ped in vehicle
        var count = 0;
        while (!p.IsUsable()) //white the ped doesnt exist yet
        {
            Wait(20);
            Log.Write(ScriptName, $"Waiting for Ped {model} to load...");
            if (count > 50) //this gives the ped a certain amount of time to spawn (count * wait time)
                break;
            count++;
        }
        Log.Write(true, "CreatePedOnSeat", "Clear ped model memory and give natural AI");
                                      //p.MarkAsNoLongerNeeded(); //lets give default AI to the ped

        unsafe
        {
            if (Native.Call<bool>(Hash.DOES_ENTITY_EXIST, p))
            {

                int handle = p.Handle;
                Native.Call(Hash.SET_ENTITY_AS_NO_LONGER_NEEDED, &handle); //lets give default AI to the ped

            }
            else
                Log.Write(true, "CreatePedOnSeat", "Entity does not exist!!!!");
        }

        return p;

    }
`

**Comment by Dilapidated** [comment] 2019-02-14 05:06
Wanted to confirm that these issues can be resolved by adding a check to IsPersistent.

This will resolve the pointer issue and windows event log error: GTA.Native.?A0x55605b1d.NativeTask.Run()

```Csharp
if (Function.Call<bool>(Hash.IS_ENTITY_A_MISSION_ENTITY, e) == false)
            {
                Log.Write("", "NEW CHECK TO AVOID POINTER CRASH");
                e.IsPersistent = false;
            }`

**Comment by crosire** [comment] 2019-02-14 18:49
Please do a pull request then!

**Comment by Dilapidated** [comment] 2019-02-14 22:38
@crosire will do, speaking with kagikn who's confirmed that same results as me. Before doing the pull request I want to ensure this fix won't cause any other issues. So far it appears there's no consequences and so looks like this old bug may be squashed.

**Comment by Dilapidated** [comment] 2019-04-20 18:33
@crosire @kagikn 

Thanks to lots of testing and help from Unknown and others I was able to figure out the best way to resolve this error and have created a gameconfig that addresses the issue here: https://www.gta5-mods.com/misc/gameconfig-xml-dilapidated 

The exact lines that need to be edited are the following:

``XML
						<Item>
							
							<PoolName>ctasksequencelist</PoolName>
							<PoolSize value="200"/>
						</Item>

						<Item>
						
							<PoolName>CEvent</PoolName>
							<PoolSize value="4000"/>
						</Item>``

**Closed** 2019-10-03 18:18 UTC
Labels: question
