### ISSUE TITLE
Euphoria stuff not working anymore

### ISSUE THREAD

**Issue by jedijosh920** [crosire/scripthookvdotnet#564] opened 2016-12-02 05:02 UTC
I heard there was gonna be a new update and was wondering if the Euphoria stuff will be fixed again? Some of my mods depend on it and it makes the user's game crash. Thanks!

**Comment by kagikn** [comment] 2016-12-16 05:32
I think memory patterns relating to Euphoria are different between those in 1.0.877.1 and those in 1.0.944.2.
POV Camera Unlocker(1.2.2) doesn't work in 1.0.944.2, so I suppose Rockstar changed the memory patterns in 1.0.944.2.

**Comment by zorg93** [comment] 2016-12-20 09:59
The siganture changed in 1.0.877.1 I dont think it was fixed in that version either and I have been busy with other projects lately

**Comment by kagikn** [comment] 2017-09-29 10:48
CamxxCore fixed some natural motion stuff in #694. So if I confirm the Euphoria class in v3 works well, I'll make PRs that are equivalent to #588 and #694, and we'll release a new version that includes these fixes.

**Closed** 2017-10-05 22:48 UTC
Labels: bug

**Comment by SH42913** [comment] 2024-01-28 10:45
Looks like it happened again, last updates changed NM patterns :(

**Comment by kagikn** [comment] 2024-01-28 13:31
@SH42913 I don't think your issue is really relevant to this issue, but are you using a nightly version? I'm aware that NM stuff in SHVDN v3.6.0 doesn't work as intended in b2802 or later.

**Comment by SH42913** [comment] 2024-01-28 14:52
Oh, I didn't know about nightly builds, I'll check it out, thanks!

**Comment by SH42913** [comment] 2024-01-28 16:39
@kagikn, thanks a lot! You're right, NM works fine in nightly builds.
