### ISSUE TITLE
New version required 

### ISSUE THREAD

**Issue by Dmitrix428** [crosire/scripthookvdotnet#920] opened 2020-04-05 20:18 UTC
**Version**
The latest version that was released  v3.0.3

**Description**
As you may know, loads of us are using Map Editors to create all kinds of projects, hundreds of communities across multiplayer clients are using the map editor and without the latest ScriptHookVDotNet, we're screwed :(

**Comment by ChemsoDev** [comment] 2020-04-05 21:12
what's the problem?
@Dmitrix428

**Comment by Dmitrix428** [comment] 2020-04-05 21:30
The map editor thing for GTA V can't be enabled and probably other modifications - following:
https://www.gta5-mods.com/scripts/map-editor
ScriptHookDotNet link:
https://www.gta5-mods.com/tools/scripthookv-net

Needs to get updated to latest version , as GTA V had an 200 MB few days ago.

**Comment by Tanjitsu** [comment] 2020-04-07 02:55
@Dmitrix428 This project is ScriptHookDotNet.
You are most likely referring to another system called ScriptHook which is a different [Website](http://www.dev-c.com/gtav/scripthookv/).

**Comment by Dmitrix428** [comment] 2020-04-07 03:09
Nah, its not the ScriptHookV, man. Its the ScriptHookDotNet that needs to get patched up to the latest version.

**Comment by Tanjitsu** [comment] 2020-04-07 17:34
ScriptHookDotNet is not required to be updated each time a new game version comes out.
If something is not working as expected then please provide detailed information.

I can confirm that i tested the map editor you linked and it loads with GTA V1.0.1868.1.
If one of the functions of the map editor is no longer working then you should speak to the mod creator. In turn the mod creator can post here if the issue is specific to ScriptHookDotNet.

Just to clarify, ScriptHookDotNet is working on GTA V1.0.1868.1

**Comment by ChemsoDev** [comment] 2020-04-08 22:30
@Dmitrix428 ye i think u should probably contact the mod dev
if there is something wrong the mod author gonna fix it or give us more technical details abt the prblm
keep up!

**Comment by Decepticon01** [comment] 2020-04-08 22:50
I'm also experiencing problems with the latest update specifically with ScriptHookVDotNet causing my game to hang on the Wasted Screen when I die in game, removing ScriptHookVDotNet clears the problem so I know it's tied to those files and the latest update.

**Comment by Dmitrix428** [comment] 2020-04-09 00:00
And its the only .asi that isn't working with Map Editor (editor that been downloaded more than 1 million times) - so if this scripthookdotnet gets updated to latest game version, I guarantee you - it'll fix all the issues.

**Comment by Tanjitsu** [comment] 2020-04-09 05:20
@Decepticon01 I have just tested with 0 mods and i did not experience my game hang.
Please remove all of your mods and scripts, then try with just ScriptHook and ScriptHookDotNet.
The issue with hanging on death will be caused by a mod loaded by ScriptHookDotNetnot by ScriptHookDotNet its self.

@Dmitrix428 The Asi loads all the dll files. So if you remove the asi then nothing happends.
You have still not provided any log or details as to a specific error.
I tested the map editor and it works.

**Comment by Decepticon01** [comment] 2020-04-09 06:00
@Tanjitsu . You are right, the game was bugging from one of the scripts loaded by  scripthookdotnet.

**Comment by ChemsoDev** [comment] 2020-04-09 12:23
@Dmitrix428 u see @Decepticon01 has no prblms now and @Tanjitsu is a contributor so he know what h'is talking abt.
try to remove everything then install scripthookv scripthookvdotnet and the map editor and i recommend u to redownload them again to make sure the files rnt corrupted.
man we r helping u so try my solution then reply.

**Comment by nitanmarcel** [comment] 2020-04-18 07:49
> And its the only .asi that isn't working with Map Editor (editor that been downloaded more than 1 million times) - so if this scripthookdotnet gets updated to latest game version, I guarantee you - it'll fix all the issues.

SHKVDN doesn't need to be updated for each version as all it does is to communicate (if I'm not wrong) with SHKV which is a totally separated project. Please notice that the latest update for the map editor was in 2015 so it could cause problems with new versions of SHKV or/and SHKVDN and an update is not going to fix any problems because there's nothing to be updated. Please contact the mod developer or find other more up-to-date alternatives of the mod you're using.

Also there's no doubt that your problem might be caused by a custom map you're using with the mod.

**Comment by nitanmarcel** [comment] 2020-04-18 09:00
Yes, after a little search on the mod page's comments I constated that this problem dates from a long time (before 2019). And many of the errors are related to NativeUI which got several updates since the release of the mod. The best hope for you is to use the NativeUI.dll that comes with the mod but at the expense of loosing compatibility with newer mods. Also there's a bug in the mod that prevents you from opening the menu with F7 which can be fixed by clearing the key bind from the game settings

 @Dmitrix428

**Closed** 2020-04-18 10:08 UTC
Labels: bug
