### ISSUE TITLE
Game crashes when I make car disappear and have the speed set at the same time

### ISSUE THREAD

**Issue by AAYapps** [crosire/scripthookvdotnet#326] opened 2015-09-21 21:18 UTC
I have been trying to get the game to stop crashing but when I put 

car.speed = 48;
car.IsVisible = false;

and when

car.speed = 48;
car.IsVisible = false;

the game crashes

Does anyone know how to fix this?

**Comment by AAYapps** [comment] 2015-09-21 21:18
The second one was supposed to be 

car.speed = 48;
car.IsVisible = true;

**Comment by letsplayordy** [comment] 2015-09-21 21:30
.speed should be capitalized.

**Comment by AAYapps** [comment] 2015-09-21 21:37
speed is capitalized. th at is not the problem

**Comment by JohnnyCrazy** [comment] 2015-09-21 21:39
Coud you pls attach/post your error logs? (ScriptHookVDotNet and ScriptHook)

**Comment by AAYapps** [comment] 2015-09-21 22:29
I don't see the log

It did not make the log file

**Comment by zorg93** [comment] 2015-09-22 21:55
Does the game crash when that code is removed?

**Comment by AAYapps** [comment] 2015-09-24 00:40
no, it does not crash

**Comment by crosire** [comment] 2015-12-21 13:54
Closing for now because does not seem to be reproducible. Please report back If the problem persists.

**Closed by crosire** 2015-12-21 13:54 UTC
Labels: question
