### ISSUE TITLE
World.CreateVehicle() gives me null

### ISSUE THREAD

**Issue by Nacorpio** [crosire/scripthookvdotnet#95] opened 2015-05-18 17:32 UTC
public LootVehicle(VehicleHash model, Vector3 position) {
            _vehicle = World.CreateVehicle(new Model(model), position);
            Main.DebugText.Caption = (_vehicle == null ? "Yes" : "No");
}

Why does this give me "Yes"?

**Comment by JohnnyCrazy** [comment] 2015-05-21 16:22
Is this still a problem @Nacorpio ? Maybe it's caused by another `Main.DebugText.Caption` call?

**Comment by Nacorpio** [comment] 2015-05-21 17:55
I'm going to try it out in a bit, and we'll see.

**Comment by JohnnyCrazy** [comment] 2015-05-28 18:29
@Nacorpio Any news? :smiley:

**Comment by Nacorpio** [comment] 2015-05-28 19:49
Just a moment. I maybe just did.

**Comment by Nacorpio** [comment] 2015-05-28 19:51
How do you print something in the log again?

**Comment by JohnnyCrazy** [comment] 2015-05-28 19:57
Just use this one-liner for this test:
````c#
public void Log(object msg)
{
    File.AppendAllText("log.txt", msg + Environment.NewLine);
}
````

**Comment by Frede1012** [comment] 2015-05-28 20:21
@JohnnyCrazy Not atm :P

**Comment by JohnnyCrazy** [comment] 2015-06-04 18:45
Can I close this @Nacorpio ? :D

**Comment by crosire** [comment] 2015-06-17 18:06
Since there was no more feedback I'll close this for now.

**Closed by crosire** 2015-06-17 18:06 UTC
Labels: needs feedback
