### ISSUE TITLE
Problem with SHVDN when i am using SHVDN 3.0 and RPH both.

### ISSUE THREAD

**Issue by varunkumar2310** [crosire/scripthookvdotnet#789] opened 2018-05-24 10:10 UTC
The link contains, 4 videos and a notepad detailing what is happening
https://drive.google.com/open?id=1JTx5CHu73_-wwoTAkG7sV93X-H1vfMJu
This problem is reproducible at the scene shown in the video.

**Comment by crosire** [comment] 2019-10-02 20:17
Closing because duplicate of #759.

**Closed by crosire** 2019-10-02 20:17 UTC
Labels: duplicate
