### ISSUE TITLE
Please make Vector3 overloads for GetNearbyVehicles and GetNearbyPeds

### ISSUE THREAD

**Issue by RainerHilmer** [crosire/scripthookvdotnet#164] opened 2015-06-03 14:22 UTC
I need overloads for these two methods which take a Vector3 position as origin but not a ped.

**Comment by crosire** [comment] 2015-06-03 14:32
There is no native which can do that. Would be nice if there was.

**Comment by Frede1012** [comment] 2015-06-03 14:39
#101 is a hackish solution to that problem, as i said in that thread. 
>Not sure if this is too "hackish" of a solution to use, maybe we should wait for a better native function? Also, i agree with @crosire on the state of the commit history :-P

**Comment by RainerHilmer** [comment] 2015-06-03 19:26
Ugh that looks ugly. Thanks for the response though. :)
I don't know how much different the game engine of V is compared to IV and I'm no C++ guy but have you looked at the source of HazardX's .net script hook for GTA IV? Maybe you find something helpful.

**Comment by Frede1012** [comment] 2015-06-03 19:56
I think some functions of Hazard's scripthook are made possible by reading memory, as far as i remember.

**Comment by RainerHilmer** [comment] 2015-06-03 20:42
http://hazardx.com/files/sourcecode_of_the_gta4_net_scripthook-92

**Comment by JohnnyCrazy** [comment] 2015-06-04 00:20
Maybe implemented by #101, not sure yet

**Comment by crosire** [comment] 2015-06-04 03:05
That's not really a good solution. It would need some testing if GTAV stores peds and vehicles as continous lists in memory like GTAIV did, in which case one could fetch data from there.

**Comment by JohnnyCrazy** [comment] 2015-06-04 18:43
I will close this as a duplicate of #13

**Closed by JohnnyCrazy** 2015-06-04 18:43 UTC
Labels: pending
