### ISSUE TITLE
GTA crashing on start up

### ISSUE THREAD

**Issue by Riguy29** [crosire/scripthookvdotnet#632] opened 2017-06-24 06:09 UTC
GTA keeps crashing when I have scripthook.net installed I am not sure what the issue is I have the 2013 redistributive package x64(but I also have 2008,2012,2010,ect versions too) and have a .Netframe work 4.7. Any ideas?

**Comment by electricman226** [comment] 2017-06-24 06:31
Is anything written to ScriptHookV.log or ScriptHookVDotNet-*(date)*.log?

**Comment by aeromanov** [comment] 2017-06-24 20:44
Have the same issue: nothing in ScriptHookVDotNet-(date).log

In ScriptHookV.log:

[23:35:03] CORE: Requesting thread creation
[23:35:03] CORE: Creating threads
[23:35:04] CORE: Started control thread, id 40 active 1
[23:35:04] CORE: Started thread 'ScriptHookVDotNet.asi' (0x000007FEEB7A1490), id 41 active 1
[23:35:04] CORE: Launching main() for 'ScriptHookVDotNet.asi' (0x000007FEEB7A1490), id 41

**Comment by electricman226** [comment] 2017-06-24 20:59
Have you both removed all your mods from the game? If you remove the ScriptHookVDotNet.dll file, does the crash still happen? Are any of the mods in the scripts directory developed by you, or are they others?

**Comment by Riguy29** [comment] 2017-06-24 21:02
Do we need the ScriptHookVDOTNET.dll file it says on the download page only to copy the .asi file into the games directory. I have mods installed but none of them are developed by me also here are the logs. 
ScripthookV
// GTA V SCRIPT HOOK (build Jun 22 2017, v1.0.1103.2)
//     (C) Alexander Blade 2015-2017
[15:53:47] INIT: Started
[15:53:47] INIT: Success, game version is VER_1_0_1103_2_STEAM
[15:53:47] INIT: Registering script 'ArrestPedV.asi' (0x00007FFB4D1B2FA0)
[15:53:47] INIT: Registering script 'MeleeRiot.asi' (0x00007FFB4C329660)
[15:53:47] INIT: Registering script 'pc_trainer.asi' (0x00007FFB31CE3AE0)
[15:53:47] INIT: Registering script 'ScriptHookVDotNet.asi' (0x00007FFB37EB1490)
[15:53:57] INIT: Pool 1 extended
[15:53:57] INIT: Pool 2 extended
[15:53:57] INIT: Pool 3 extended
[15:53:57] INIT: Pool 4 extended
[15:54:02] INIT: GtaThread collection size 188
[15:54:02] INIT: wnd proc 0x00000000FFFF0BEF
[15:54:02] INIT: IDXGISwapChain 0x00007FFB75B90AA0 (0x00007FFB75B33610)
[15:54:02] INIT: IDXGISwapChain set
[15:54:03] INIT: DX init started
[15:54:03] INIT: DX feature level B000
[15:54:03] INIT: DX init succeeded
[15:54:43] CORE: Requesting thread creation
[15:54:43] CORE: Creating threads
[15:54:43] CORE: Started control thread, id 28 active 1
[15:54:43] CORE: Started thread 'ArrestPedV.asi' (0x00007FFB4D1B2FA0), id 29 active 1
[15:54:43] CORE: Started thread 'MeleeRiot.asi' (0x00007FFB4C329660), id 30 active 1
[15:54:43] CORE: Started thread 'pc_trainer.asi' (0x00007FFB31CE3AE0), id 31 active 1
[15:54:43] CORE: Started thread 'ScriptHookVDotNet.asi' (0x00007FFB37EB1490), id 32 active 1
[15:54:43] CORE: Launching main() for 'ArrestPedV.asi' (0x00007FFB4D1B2FA0), id 29
[15:54:43] CORE: Launching main() for 'MeleeRiot.asi' (0x00007FFB4C329660), id 30
[15:54:43] CORE: Launching main() for 'pc_trainer.asi' (0x00007FFB31CE3AE0), id 31
[15:54:43] CORE: Launching main() for 'ScriptHookVDotNet.asi' (0x00007FFB37EB1490), id 32
ScripHookVDotNET
[15:54:44] [DEBUG] Created script domain 'ScriptDomain_1DFE73AE' with v2.9.6.
[15:54:44] [DEBUG] Loading scripts from 'C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V\scripts' into script domain 'ScriptDomain_1DFE73AE' ...
[15:54:44] [DEBUG] Found 3 script(s) in 'gTaTer_HostagesV.dll'.
[15:54:44] [DEBUG] Found 0 script(s) in 'NativeUI.dll'.
[15:54:44] [DEBUG] Starting 3 script(s) ...
[15:54:44] [DEBUG] Instantiating script 'gTaTer_HostagesV.Hostage' in script domain 'ScriptDomain_1DFE73AE' ...
[15:54:44] [ERROR] Failed to instantiate script 'gTaTer_HostagesV.Hostage' because no public default constructor was found.
[15:54:44] [DEBUG] Instantiating script 'gTaTer_HostagesV.Main' in script domain 'ScriptDomain_1DFE73AE' ...
[15:54:44] [DEBUG] Started script 'gTaTer_HostagesV.Main'.
[15:54:44] [DEBUG] Instantiating script 'gTaTer_HostagesV.PMenu' in script domain 'ScriptDomain_1DFE73AE' ...
[15:54:44] [DEBUG] Started script 'gTaTer_HostagesV.PMenu'.
[15:56:28] [ERROR] Caught unhandled exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at gTaTer_HostagesV.Hostage.GetOnKnees(Hostage hostage)
   at gTaTer_HostagesV.Main.KeyPress(Object sender, KeyEventArgs e)
   at GTA.Script.raise_KeyDown(Object value0, KeyEventArgs value1)
   at GTA.Script.MainLoop()

**Comment by electricman226** [comment] 2017-06-24 21:08
`gTaTer_HostagesV.dll` is throwing an exception, but it's unlikely this is the cause.
You also seem to have quite a few ScriptHookV mods; read below.

That's my bad for the confusion, you don't need ScriptHookVDotNet.dll, only the ASI file. Try removing `ScriptHookVDotNet.asi` from the game directory to see if you still crash. If you do, it's related to a different ScriptHookV mod.

**Comment by Riguy29** [comment] 2017-06-24 21:18
Ok I removed ScripthookVDotNet.asi from my directory and I no longer crash

**Comment by electricman226** [comment] 2017-06-24 21:34
Try removing `gTaTer_HostagesV.dll` from the scripts directory. This is most likely the cause of the crash. Don't forget to put `ScriptHookVDotNet.asi` back into the game directory.

**Comment by Riguy29** [comment] 2017-06-24 21:54
I took the Hostages mod out of the scripts directory and it still crashes.

**Comment by Riguy29** [comment] 2017-06-24 22:01
Ok I just got it to work but for no apparent reason I loaded it up a couple of times with the all the mods and stuff on it it crashed the first 2 times but on the 3rd it worked no idea why I did change anything between the 3 different start ups

**Comment by electricman226** [comment] 2017-06-24 22:36
Have you been tabbing out during the loading screen?

**Comment by Riguy29** [comment] 2017-06-24 23:02
yes

**Comment by crosire** [comment] 2017-07-26 17:45
Closing for now, until findings of OP are updated to the latest SHVDN version.

**Closed by crosire** 2017-07-26 17:45 UTC
