### ISSUE TITLE
Need a way to give a Ped a parachute

### ISSUE THREAD

**Issue by bdking00** [crosire/scripthookvdotnet#468] opened 2016-05-18 23:47 UTC
This seems like something that should already be in, and I think it would be a good idea to add this.

**Comment by tetchel** [comment] 2016-05-20 00:30
If you CTRL+F Parachute in NativeDB, there are a number of parachute-related functions that take a Ped as parameter (ignore the ones that take a Player). I would suggest trying some of these, eg 
`AI::TASK_PARACHUTE,` PED::FORCE_PED_TO_OPEN_PARACHUTE, PED::GET_PED_PARACHUTE_STATE.`

I don't see any way to "give" a parachute though, which I do find surprising.

**Comment by zorg93** [comment] 2016-05-21 07:42
If you're a story mode character, you can give the parachute using
`set_ped_component_Variation(Game.Player.char, component,  index, 0, 0);`

where component, index = 9, 5 if playing as micheal. 8, 1 if franklin and 8, 3 if trevor. However this causes your ped to immediately take the parachute off like you've just landed. The issue is a config/reset flag needing setting i think. Have a look around in the bj.c4 file from decompiled scripts. the answer will be in there most likely

**Comment by kagikn** [comment] 2016-05-21 10:07
That's easy.
```
Functions.Call(GIVE_WEAPON_TO_PED, ped, Game.GenrateHash(GADGET_PARACHUTE), 1, false, false);
```
or
```
ped.Weapons.Give((WeaponHash)0xA720365C, 1, false, false);
```

**Comment by zorg93** [comment] 2016-05-21 12:34
Oh Just giving it, not actually putting the parachute on

**Comment by JohnnyCrazy** [comment] 2016-05-21 14:01
@kagikn `0xA720365C` is night-vision. `0xFBAB5776` is the parachute. gonna add those the weapon hashes

**Comment by kagikn** [comment] 2016-05-21 14:03
Oops, I saw them wrong.

**Comment by crosire** [comment] 2016-05-24 16:26
Added in 261f4e9bfc2c1d7f72070538b44d5ca256aab16f.

**Closed by crosire** 2016-05-24 16:26 UTC
