### ISSUE TITLE
ScriptHookVDotNet crash in LSPDFR

### ISSUE THREAD

**Issue by Mxske** [crosire/scripthookvdotnet#1217] opened 2023-05-10 17:42 UTC
**Version**
All

**Description**
When i try to put the scripthookvdotnet files into my modded gta 5 folder (lspdfr) it will crash everytime.
the only thing i did was putting it in and then boom! it crashed.
i looked at the logs and it didn't look like anything was wrong.

[RagePluginHook.log](https://github.com/crosire/scripthookvdotnet/files/11444662/RagePluginHook.log)
[ScriptHookV.log](https://github.com/crosire/scripthookvdotnet/files/11444663/ScriptHookV.log)
[ScriptHookVDotNet.log](https://github.com/crosire/scripthookvdotnet/files/11444664/ScriptHookVDotNet.log)

i also looked at the openiv.log file and i didn't found anything unnormal in there

**Comment by kagikn** [comment] 2023-05-10 18:37
I believe this issue cannot be reproduced with a build since #1167 has been merged, so I'll close this one. I don't think the game will crash immediately by just having ScriptHookVDotNet and RPH run at the same time without any scripts or plugins even if SHVDN version is v3.6.0 though.

I assume you are using the release version of v3.6.0 of ScriptHookVDotNet since you haven't clarified the exact version you are using and no one bother to suggest you try using AppVeyor builds of SHVDN in RPH Discord.

I can run LSPDFR stably with the build 08bebed. The game will crash when an unhandled exception is thrown in one of RPH AppDomains if I use v3.6.0 of SHVDN as you would expect.

If you have used AppVeyor builds and this issue can be reproduced even with builds later than 29ba91e, feel free to reopen.

**Closed by kagikn** 2023-05-10 18:37 UTC
Labels: bug
