### ISSUE TITLE
Problem with Game.GetUserInput

### ISSUE THREAD

**Issue by RainerHilmer** [crosire/scripthookvdotnet#259] opened 2015-07-22 17:40 UTC
I have created a configuration menu for my Autodrive mod. Now at all value types I call Game.GetUserInput so the user can enter a new value. After pressing the return/enter key I expect the input line to close and the menu should reappear but instead the input line just pops up again. I guess I'm just doing something wrong. So here is a bit of code. ChangeCarMoversPerimeter is called when the user hits return on the appropriate menu item.
```cs
      private void ChangeCarMoversPerimeter()
      {
         UI.ShowSubtitle("Enter new perimeter value in meters.");
         int number;
         var success = int.TryParse(
            Game.GetUserInput(
               _currentConfig.CarMoversPerimeter
                  .ToString(CultureInfo.InvariantCulture), 3), out number);
         if(success)
            _currentConfig.CarMoversPerimeter = number;
         else
            UI.ShowSubtitle("That's not a valid number!");
         ReOpenMainMenuAt(_currentlySelectedIndex);
         DisplayAndSafeNewSettingOf("CarMoversPerimeter", _currentConfig.CarMoversPerimeter);
      }
//...
      private void ReOpenMainMenuAt(int index)
      {
         _currentlySelectedIndex = index;
         View.AddMenu(_mainMenu);
         _keyMenuIsOpen = false;
         _mainMenuIsOpen = true;
         _mainMenu.Items[0].Deselect();
         _mainMenu.SelectedIndex = index;
         _mainMenu.Items[index].Select();
         OnMainMenuSelectedIndexChanged(new SelectedIndexChangedArgs(index));
      }
```

**Comment by RainerHilmer** [comment] 2015-07-22 17:54
Got it. It turned out it was the key bindings for the menu handling.
...
//ActivateKey = Keys.Return;
         //BackKey = Keys.Escape;
         //DownKey = Keys.Down;
         //LeftKey = Keys.Left;
         //RightKey = Keys.Right;
         //UpKey = Keys.Up;
...
All is good after commenting them out. Looks like I need to unsubscribe from the key event or the return key on GetUserInput is also used to activate the menu item again, which causes this kind of loop.

**Comment by IncoCode** [comment] 2015-07-22 17:59
I think we shouldn't process menu keys if GetUserInput is activated.

**Comment by RainerHilmer** [comment] 2015-07-22 18:24
I was too happy too soon. Sometimes it works but most of the times not.
@IncoCode You mean I should unsubscribe from all menu related events before I call GetUserInput?

**Comment by IncoCode** [comment] 2015-07-22 18:38
@RainerHilmer i mean add check here: https://github.com/crosire/scripthookvdotnet/blob/dev/source/Script.cpp#L161
```c++
if (UserInputActivated) return; // i forgot the proper name of this native :D
```
or something.

**Comment by JohnnyCrazy** [comment] 2015-07-22 18:58
Feature-Duplicate of #252.

Also, do you increment `_currentlySelectedIndex` anywhere?

**Comment by RainerHilmer** [comment] 2015-07-22 19:15
Increment? No, _currentlySelectedIndex gets set in the SelectedIndexChanged handler.
      private void OnMainMenuSelectedIndexChanged(SelectedIndexChangedArgs e)
      {
         _currentlySelectedIndex = e.SelectedIndex;
         var propertyValue = GetPropertyValueForSelectedMainMenuIndex(e.SelectedIndex);
         if(string.IsNullOrEmpty(propertyValue.ToString()))
         {
            UI.ShowSubtitle(""); //removes the previous display.
            return;
         }
         UI.ShowSubtitle(_mainMenuItems[e.SelectedIndex].Caption
                         + IS_CURRENTLY + GetPropertyValueForSelectedMainMenuIndex(e.SelectedIndex));
      }

@IncoCode Oh now I get you. Your reply was not directed towards me but to the team. So there is nothing I can do about it?

**Comment by RainerHilmer** [comment] 2015-07-23 20:07
Any idea for a workaround? The users are waiting for the release of V5.0.0 of VAutodrive and I promised them an in-game configuration menu.

**Comment by JohnnyCrazy** [comment] 2015-07-23 20:27
Just disable all the menu keys and restore them after the input is closed?

**Comment by RainerHilmer** [comment] 2015-07-23 21:58
I found the culprit. It's not only the menu keys but also the line I commented out here:
...
      private void ReOpenMainMenuAt(int index)
      {
         _currentlySelectedIndex = index;
         View.AddMenu(_mainMenu);
         _keyMenuIsOpen = false;
         _mainMenuIsOpen = true;
         _mainMenu.Items[0].Deselect();
         //_mainMenu.SelectedIndex = index;
         _mainMenu.Items[index].Select();
         OnMainMenuSelectedIndexChanged(new SelectedIndexChangedArgs(index));
      }
...
So is there any other way to highlight a certain menu element without the SelectedIndexChanged event being fired? It's this event that calls ChangeCarMoversPerimeter again and so I end up in a loop. Hmm I could detach that event and attach it again after the selction. I'll be back with the result...

**Comment by zorg93** [comment] 2015-09-01 23:31
This issue can be closed now

**Closed** 2015-09-02 08:13 UTC
Labels: question
