### ISSUE TITLE
World.GetAllPeds and World.GetNearbyPeds crashes game

### ISSUE THREAD

**Issue by xcxooxl** [crosire/scripthookvdotnet#802] opened 2018-07-28 19:28 UTC
Both of those functions crashes the game for me, Not sure if there is a different way to get nearby peds.

**Comment by Tanjitsu** [comment] 2019-04-22 23:52
Probably  #758

**Comment by Cr1TiKa7** [comment] 2019-05-28 21:45
Made a little research and found that the issue is in line 570/571 in the NativeMemory.cs. Propably a wrong pattern? maybe @kagikn can fix this

**Comment by crosire** [comment] 2019-10-03 18:23
Closing as duplicate of #758.

**Closed by crosire** 2019-10-03 18:23 UTC
Labels: bug, duplicate
